workflows:
  ios-release:
    name: Osvan iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: NaijaGo App LTD

    environment:
      flutter: 3.41.7
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.osvan.fintech

    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles
        script: xcode-project use-profiles

      - name: Get packages
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ipa --release

      - name: Check IPA file
        script: |
          ls -R build/ios/ipa

    artifacts:
      - build/ios/ipa/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
